### ISSUE TITLE
Error while running fuzzing campaigns from scratch

### ISSUE THREAD

**Issue by cniddodi** [HexHive/SieveFuzz#2]
Running the command `python3 create_fuzz_script.py -c aflxgo.config -n 15 --flush ` 
in Section [https://github.com/HexHive/SieveFuzz/tree/main/artifact#comparative-evaluation-against-afl-and-aflgo-estimated-time-280-cpu-days](url) results in the following error:
```
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

Seems like the python script isn't able to connect with the 'host' network due to some docker container configuration issue?

**Comment by prashast** [comment]
Hi, based on your error message it seems like the beanstalk server may not be running. 
Can you confirm that its setup? You can run it inside your docker container with the following command: `beanstalkd &`. After that the job deployment scripts should start working as expected.

**Comment by cniddodi** [comment]
> You can run it inside your docker container with the following command: `beanstalkd &`.

Thanks! That was the missing command. Now connection request succeeds.
